services:

  db_core:
    image: postgres:16
    container_name: workoutracker
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]

volumes:
  app:
  pgdata: